[aliases]
shrug = "Â¯\\_(ãƒ„)_/Â¯"
Alpha = "Î‘"
Beta = "Î’"
Chi = "Î§"
Delta = "Î”"
Epsilon = "Î•"
Eta = "Î—"
Gamma = "Î“"
Iota = "Î™"
Kappa = "Îš"
Lambda = "Î›"
Mu = "Îœ"
Nu = "Î"
Omega = "Î©"
Omicron = "ÎŸ"
Phi = "Î¦"
Pi = "Î "
Psi = "Î¨"
Rho = "Î¡"
Sigma = "Î£"
Tau = "Î¤"
Theta = "Î˜"
Upsilon = "Î¥"
Xi = "Î"
Zeta = "Î–"
absmul = "â¨‚"
absop = "â¨€"
abssum = "â¨"
aleph = "â„µ"
alpha = "Î±"
and = "âˆ§"
aprox = "âˆ¼"
aproxeq = "â‰ƒ"
assertion = "âŠ¦"
because = "âˆµ"
beta = "Î²"
bottom = "âŠ¥"
btc = "à¸¿"
cdot = "â‹…"
cdots = "â‹¯"
chi = "Ï‡"
cong = "â‰¡"
contradiction = "â†¯"
delta = "Î´"
divides = "âˆ£"
dotminus = "âˆ¸"
emptyset = "âˆ…"
epsilon = "Îµ"
"eq?" = "â‰Ÿ"
eqdef = "â‰"
eqtriang = "â‰œ"
equiv = "â‡”"
eta = "Î·"
euro = "â‚¬"
exists = "âˆƒ"
forall = "âˆ€"
gamma = "Î³"
geq = "â‰¥"
implies = "â‡’"
in = "âˆˆ"
inf = "âˆ"
integral = "âˆ«"
intersect = "âˆ©"
ints = "â„¤"
iota = "Î¹"
kappa = "Îº"
lambda = "Î»"
larrow = "â†"
lceil = "âŒˆ"
ldsqbracket = "âŸ¦"
leq = "â‰¤"
lfloor = "âŒŠ"
lseq = "âŸ¨"
mapsto = "â†¦"
models = "âŠ§"
mu = "Î¼"
nabla = "âˆ‡"
nats = "â„•"
neq = "â‰ "
not = "Â¬"
notaproxeq = "â‰„"
notdivides = "âˆ¤"
notexists = "âˆ„"
notin = "âˆ‰"
notsubset = "âŠ„"
notsubseteq = "âŠˆ"
nu = "Î½"
omega = "Ï‰"
omicron = "Î¿"
or = "âˆ¨"
part = "âˆ‚"
phi = "Ï†"
pi = "Ï€"
plusminus = "Â±"
prec = "â‰º"
preceq = "â‰¼"
prod = "âˆ"
psi = "Ïˆ"
qed = "â–¡"
rarrow = "â†’"
rats = "â„š"
rceil = "âŒ‰"
rdsqbracket = "âŸ§"
reals = "â„"
rfloor = "âŒ‹"
rho = "Ï"
rotleft = "â‰ª"
rotright = "â‰«"
rseq = "âŸ©"
sigma = "Ïƒ"
subset = "âŠ‚"
subseteq = "âŠ†"
subsetneq = "âŠŠ"
succ = "â‰»"
succeq = "â‰½"
sum = "âˆ‘"
tau = "Ï„"
therefore = "âˆ´"
theta = "Î¸"
tm = "â„¢"
top = "âŠ¤"
union = "âˆª"
upsilon = "Ï…"
vdots = "â‹®"
xi = "Î¾"
xor = "â¨"
zeta = "Î¶"
ib = "â€½"
dagger = "â€ "
doubledagger = "â€¡"
warning = "âš "
skull = "ğŸ’€"
skullcrossbones = "â˜ "
lquote = "â€œ"
rquote = "â€"
lsquote = "â€˜"
rsquote = "â€™"
ratio = "âˆ¶"
copyright = "Â©"
copyleft = "ğŸ„¯"
dash = "â€”"
